### PR TITLE
Windows service

### PR DESCRIPTION
**Pull request by adbertram**

### CODE REVIEW

**Comment by mabouchard-dev** [comment]
@adbertram Hi I was testing your script and I see that you have a ServiceName property. To be compatible with our old Windows service reset system and avoid client configuration. Could you make the script reset all the services it finds that run with the users?

**Comment by adbertram** [comment]
@mabouchard-dev ServiceName should be optional. If the user provides it, it'll only look for that service otherwise, it'll look for all services running under that username.

**Comment by mabouchard-dev** [comment]
@adbertram Hi, you're right, it works this way. I didn't look at the script but only read the read me. I tested it and it works well I will merge it. My only comment would be to adjust the read me to indicate that if the field is empty, we will reset all the services that are run by the user. Thanks.

**Review by mabouchard-dev — APPROVED** [review]
LGTM

**Pull request merged**
